//
// Makes the value of GTL_TARGET_NAMESPACE a prefix for all GTL
// library class names
//

//
// To avoid global namespace issues, define GTL_TARGET_NAMESPACE to a short
// string in your target if you are using the GTL library in a shared-code
// environment like a plug-in.
//
// For example:   -DGTL_TARGET_NAMESPACE=MyPlugin
//

//
// com.google.GTLFramework v. 2.0 (208 classes) 2011-05-22 23:09:44 -0400
//

#if defined(__OBJC__) && defined(GTL_TARGET_NAMESPACE)

  #define _GTL_NS_SYMBOL_INNER(ns, symbol) ns ## _ ## symbol
  #define _GTL_NS_SYMBOL_MIDDLE(ns, symbol) _GTL_NS_SYMBOL_INNER(ns, symbol)
  #define _GTL_NS_SYMBOL(symbol) _GTL_NS_SYMBOL_MIDDLE(GTL_TARGET_NAMESPACE, symbol)

  #define _GTL_NS_STRING_INNER(ns) #ns
  #define _GTL_NS_STRING_MIDDLE(ns) _GTL_NS_STRING_INNER(ns)
  #define GTL_TARGET_NAMESPACE_STRING _GTL_NS_STRING_MIDDLE(GTL_TARGET_NAMESPACE)

  #define GTLBatchQuery                                               _GTL_NS_SYMBOL(GTLBatchQuery)
  #define GTLBatchResult                                              _GTL_NS_SYMBOL(GTLBatchResult)
  #define GTLBooksBookshelf                                           _GTL_NS_SYMBOL(GTLBooksBookshelf)
  #define GTLBooksBookshelves                                         _GTL_NS_SYMBOL(GTLBooksBookshelves)
  #define GTLBooksReadingPosition                                     _GTL_NS_SYMBOL(GTLBooksReadingPosition)
  #define GTLBooksReview                                              _GTL_NS_SYMBOL(GTLBooksReview)
  #define GTLBooksReviewAuthor                                        _GTL_NS_SYMBOL(GTLBooksReviewAuthor)
  #define GTLBooksReviewSource                                        _GTL_NS_SYMBOL(GTLBooksReviewSource)
  #define GTLBooksVolume                                              _GTL_NS_SYMBOL(GTLBooksVolume)
  #define GTLBooksVolumeAccessInfo                                    _GTL_NS_SYMBOL(GTLBooksVolumeAccessInfo)
  #define GTLBooksVolumeAccessInfoEpub                                _GTL_NS_SYMBOL(GTLBooksVolumeAccessInfoEpub)
  #define GTLBooksVolumeAccessInfoPdf                                 _GTL_NS_SYMBOL(GTLBooksVolumeAccessInfoPdf)
  #define GTLBooksVolumes                                             _GTL_NS_SYMBOL(GTLBooksVolumes)
  #define GTLBooksVolumeSaleInfo                                      _GTL_NS_SYMBOL(GTLBooksVolumeSaleInfo)
  #define GTLBooksVolumeSaleInfoListPrice                             _GTL_NS_SYMBOL(GTLBooksVolumeSaleInfoListPrice)
  #define GTLBooksVolumeSaleInfoRetailPrice                           _GTL_NS_SYMBOL(GTLBooksVolumeSaleInfoRetailPrice)
  #define GTLBooksVolumeUserInfo                                      _GTL_NS_SYMBOL(GTLBooksVolumeUserInfo)
  #define GTLBooksVolumeVolumeInfo                                    _GTL_NS_SYMBOL(GTLBooksVolumeVolumeInfo)
  #define GTLBooksVolumeVolumeInfoDimensions                          _GTL_NS_SYMBOL(GTLBooksVolumeVolumeInfoDimensions)
  #define GTLBooksVolumeVolumeInfoImageLinks                          _GTL_NS_SYMBOL(GTLBooksVolumeVolumeInfoImageLinks)
  #define GTLBooksVolumeVolumeInfoIndustryIdentifiersItem             _GTL_NS_SYMBOL(GTLBooksVolumeVolumeInfoIndustryIdentifiersItem)
  #define GTLCollectionObject                                         _GTL_NS_SYMBOL(GTLCollectionObject)
  #define GTLDateTime                                                 _GTL_NS_SYMBOL(GTLDateTime)
  #define GTLErrorObject                                              _GTL_NS_SYMBOL(GTLErrorObject)
  #define GTLErrorObjectData                                          _GTL_NS_SYMBOL(GTLErrorObjectData)
  #define GTLJSONParser                                               _GTL_NS_SYMBOL(GTLJSONParser)
  #define GTLLatitudeLocation                                         _GTL_NS_SYMBOL(GTLLatitudeLocation)
  #define GTLLatitudeLocationFeed                                     _GTL_NS_SYMBOL(GTLLatitudeLocationFeed)
  #define GTLModeratorProfile                                         _GTL_NS_SYMBOL(GTLModeratorProfile)
  #define GTLModeratorProfileAttribution                              _GTL_NS_SYMBOL(GTLModeratorProfileAttribution)
  #define GTLModeratorProfileAttributionGeo                           _GTL_NS_SYMBOL(GTLModeratorProfileAttributionGeo)
  #define GTLModeratorProfileId                                       _GTL_NS_SYMBOL(GTLModeratorProfileId)
  #define GTLModeratorSeries                                          _GTL_NS_SYMBOL(GTLModeratorSeries)
  #define GTLModeratorSeriesCounters                                  _GTL_NS_SYMBOL(GTLModeratorSeriesCounters)
  #define GTLModeratorSeriesId                                        _GTL_NS_SYMBOL(GTLModeratorSeriesId)
  #define GTLModeratorSeriesList                                      _GTL_NS_SYMBOL(GTLModeratorSeriesList)
  #define GTLModeratorSubmission                                      _GTL_NS_SYMBOL(GTLModeratorSubmission)
  #define GTLModeratorSubmissionAttribution                           _GTL_NS_SYMBOL(GTLModeratorSubmissionAttribution)
  #define GTLModeratorSubmissionCounters                              _GTL_NS_SYMBOL(GTLModeratorSubmissionCounters)
  #define GTLModeratorSubmissionGeo                                   _GTL_NS_SYMBOL(GTLModeratorSubmissionGeo)
  #define GTLModeratorSubmissionId                                    _GTL_NS_SYMBOL(GTLModeratorSubmissionId)
  #define GTLModeratorSubmissionList                                  _GTL_NS_SYMBOL(GTLModeratorSubmissionList)
  #define GTLModeratorSubmissionParentSubmissionId                    _GTL_NS_SYMBOL(GTLModeratorSubmissionParentSubmissionId)
  #define GTLModeratorSubmissionTranslationsItem                      _GTL_NS_SYMBOL(GTLModeratorSubmissionTranslationsItem)
  #define GTLModeratorTag                                             _GTL_NS_SYMBOL(GTLModeratorTag)
  #define GTLModeratorTagId                                           _GTL_NS_SYMBOL(GTLModeratorTagId)
  #define GTLModeratorTagList                                         _GTL_NS_SYMBOL(GTLModeratorTagList)
  #define GTLModeratorTopic                                           _GTL_NS_SYMBOL(GTLModeratorTopic)
  #define GTLModeratorTopic2                                          _GTL_NS_SYMBOL(GTLModeratorTopic2)
  #define GTLModeratorTopic2Counters                                  _GTL_NS_SYMBOL(GTLModeratorTopic2Counters)
  #define GTLModeratorTopic2Id                                        _GTL_NS_SYMBOL(GTLModeratorTopic2Id)
  #define GTLModeratorTopic2Rules                                     _GTL_NS_SYMBOL(GTLModeratorTopic2Rules)
  #define GTLModeratorTopic2RulesSubmissions                          _GTL_NS_SYMBOL(GTLModeratorTopic2RulesSubmissions)
  #define GTLModeratorTopic2RulesVotes                                _GTL_NS_SYMBOL(GTLModeratorTopic2RulesVotes)
  #define GTLModeratorTopicCounters                                   _GTL_NS_SYMBOL(GTLModeratorTopicCounters)
  #define GTLModeratorTopicId                                         _GTL_NS_SYMBOL(GTLModeratorTopicId)
  #define GTLModeratorTopicList                                       _GTL_NS_SYMBOL(GTLModeratorTopicList)
  #define GTLModeratorTopicRules                                      _GTL_NS_SYMBOL(GTLModeratorTopicRules)
  #define GTLModeratorTopicRulesSubmissions                           _GTL_NS_SYMBOL(GTLModeratorTopicRulesSubmissions)
  #define GTLModeratorTopicRulesVotes                                 _GTL_NS_SYMBOL(GTLModeratorTopicRulesVotes)
  #define GTLModeratorTopicsResourcePartial                           _GTL_NS_SYMBOL(GTLModeratorTopicsResourcePartial)
  #define GTLModeratorTopicsResourcePartialId                         _GTL_NS_SYMBOL(GTLModeratorTopicsResourcePartialId)
  #define GTLModeratorVote                                            _GTL_NS_SYMBOL(GTLModeratorVote)
  #define GTLModeratorVoteId                                          _GTL_NS_SYMBOL(GTLModeratorVoteId)
  #define GTLModeratorVoteList                                        _GTL_NS_SYMBOL(GTLModeratorVoteList)
  #define GTLModeratorVotesResourcePartial                            _GTL_NS_SYMBOL(GTLModeratorVotesResourcePartial)
  #define GTLObject                                                   _GTL_NS_SYMBOL(GTLObject)
  #define GTLPlusOneAcl                                               _GTL_NS_SYMBOL(GTLPlusOneAcl)
  #define GTLPlusOneAclItemsItem                                      _GTL_NS_SYMBOL(GTLPlusOneAclItemsItem)
  #define GTLPlusOneActivity                                          _GTL_NS_SYMBOL(GTLPlusOneActivity)
  #define GTLPlusOneActivityActor                                     _GTL_NS_SYMBOL(GTLPlusOneActivityActor)
  #define GTLPlusOneActivityActorImage                                _GTL_NS_SYMBOL(GTLPlusOneActivityActorImage)
  #define GTLPlusOneActivityCategoriesItem                            _GTL_NS_SYMBOL(GTLPlusOneActivityCategoriesItem)
  #define GTLPlusOneActivityFeed                                      _GTL_NS_SYMBOL(GTLPlusOneActivityFeed)
  #define GTLPlusOneActivityFeedLinksItem                             _GTL_NS_SYMBOL(GTLPlusOneActivityFeedLinksItem)
  #define GTLPlusOneActivityLinksItem                                 _GTL_NS_SYMBOL(GTLPlusOneActivityLinksItem)
  #define GTLPlusOneActivityObject                                    _GTL_NS_SYMBOL(GTLPlusOneActivityObject)
  #define GTLPlusOneActivityObjectActor                               _GTL_NS_SYMBOL(GTLPlusOneActivityObjectActor)
  #define GTLPlusOneActivityObjectActorImage                          _GTL_NS_SYMBOL(GTLPlusOneActivityObjectActorImage)
  #define GTLPlusOneActivityObjectAttachmentsItem                     _GTL_NS_SYMBOL(GTLPlusOneActivityObjectAttachmentsItem)
  #define GTLPlusOneActivityObjectAttachmentsItemLinksItem            _GTL_NS_SYMBOL(GTLPlusOneActivityObjectAttachmentsItemLinksItem)
  #define GTLPlusOneActivityObjectLinksItem                           _GTL_NS_SYMBOL(GTLPlusOneActivityObjectLinksItem)
  #define GTLPlusOneActivityObjectPlusoners                           _GTL_NS_SYMBOL(GTLPlusOneActivityObjectPlusoners)
  #define GTLPlusOneActivityObjectReplies                             _GTL_NS_SYMBOL(GTLPlusOneActivityObjectReplies)
  #define GTLPlusOneActivityObjectResharers                           _GTL_NS_SYMBOL(GTLPlusOneActivityObjectResharers)
  #define GTLPlusOneActivityProvider                                  _GTL_NS_SYMBOL(GTLPlusOneActivityProvider)
  #define GTLPlusOneAlbum                                             _GTL_NS_SYMBOL(GTLPlusOneAlbum)
  #define GTLPlusOneAlbumOwner                                        _GTL_NS_SYMBOL(GTLPlusOneAlbumOwner)
  #define GTLPlusOneAlbumOwnerImage                                   _GTL_NS_SYMBOL(GTLPlusOneAlbumOwnerImage)
  #define GTLPlusOneAlbumPhotos                                       _GTL_NS_SYMBOL(GTLPlusOneAlbumPhotos)
  #define GTLPlusOneAlbumsFeed                                        _GTL_NS_SYMBOL(GTLPlusOneAlbumsFeed)
  #define GTLPlusOneAlbumVideos                                       _GTL_NS_SYMBOL(GTLPlusOneAlbumVideos)
  #define GTLPlusOneCircle                                            _GTL_NS_SYMBOL(GTLPlusOneCircle)
  #define GTLPlusOneCircleFeed                                        _GTL_NS_SYMBOL(GTLPlusOneCircleFeed)
  #define GTLPlusOneCircleFeedLinks                                   _GTL_NS_SYMBOL(GTLPlusOneCircleFeedLinks)
  #define GTLPlusOneCircleFeedLinksLinkItem                           _GTL_NS_SYMBOL(GTLPlusOneCircleFeedLinksLinkItem)
  #define GTLPlusOneCircleLinks                                       _GTL_NS_SYMBOL(GTLPlusOneCircleLinks)
  #define GTLPlusOneCircleLinksSelfItem                               _GTL_NS_SYMBOL(GTLPlusOneCircleLinksSelfItem)
  #define GTLPlusOneCirclePeople                                      _GTL_NS_SYMBOL(GTLPlusOneCirclePeople)
  #define GTLPlusOneComment                                           _GTL_NS_SYMBOL(GTLPlusOneComment)
  #define GTLPlusOneCommentActor                                      _GTL_NS_SYMBOL(GTLPlusOneCommentActor)
  #define GTLPlusOneCommentActorImage                                 _GTL_NS_SYMBOL(GTLPlusOneCommentActorImage)
  #define GTLPlusOneCommentFeed                                       _GTL_NS_SYMBOL(GTLPlusOneCommentFeed)
  #define GTLPlusOneCommentFeedLinks                                  _GTL_NS_SYMBOL(GTLPlusOneCommentFeedLinks)
  #define GTLPlusOneCommentFeedLinksLinkItem                          _GTL_NS_SYMBOL(GTLPlusOneCommentFeedLinksLinkItem)
  #define GTLPlusOneCommentLinksItem                                  _GTL_NS_SYMBOL(GTLPlusOneCommentLinksItem)
  #define GTLPlusOneCommentObject                                     _GTL_NS_SYMBOL(GTLPlusOneCommentObject)
  #define GTLPlusOneCountFeed                                         _GTL_NS_SYMBOL(GTLPlusOneCountFeed)
  #define GTLPlusOneCountFeedCounts                                   _GTL_NS_SYMBOL(GTLPlusOneCountFeedCounts)
  #define GTLPlusOneCountFeedCountsCountItem                          _GTL_NS_SYMBOL(GTLPlusOneCountFeedCountsCountItem)
  #define GTLPlusOneGadget                                            _GTL_NS_SYMBOL(GTLPlusOneGadget)
  #define GTLPlusOneLink                                              _GTL_NS_SYMBOL(GTLPlusOneLink)
  #define GTLPlusOnePeopleFeed                                        _GTL_NS_SYMBOL(GTLPlusOnePeopleFeed)
  #define GTLPlusOnePerson                                            _GTL_NS_SYMBOL(GTLPlusOnePerson)
  #define GTLPlusOnePerson2                                           _GTL_NS_SYMBOL(GTLPlusOnePerson2)
  #define GTLPlusOnePerson2AccountsItem                               _GTL_NS_SYMBOL(GTLPlusOnePerson2AccountsItem)
  #define GTLPlusOnePerson2CirclesItem                                _GTL_NS_SYMBOL(GTLPlusOnePerson2CirclesItem)
  #define GTLPlusOnePerson2EmailsItem                                 _GTL_NS_SYMBOL(GTLPlusOnePerson2EmailsItem)
  #define GTLPlusOnePerson2Image                                      _GTL_NS_SYMBOL(GTLPlusOnePerson2Image)
  #define GTLPlusOnePerson2Name                                       _GTL_NS_SYMBOL(GTLPlusOnePerson2Name)
  #define GTLPlusOnePerson2OrganizationsItem                          _GTL_NS_SYMBOL(GTLPlusOnePerson2OrganizationsItem)
  #define GTLPlusOnePerson2PhoneNumbersItem                           _GTL_NS_SYMBOL(GTLPlusOnePerson2PhoneNumbersItem)
  #define GTLPlusOnePerson2PlacesLivedItem                            _GTL_NS_SYMBOL(GTLPlusOnePerson2PlacesLivedItem)
  #define GTLPlusOnePerson2UrlsItem                                   _GTL_NS_SYMBOL(GTLPlusOnePerson2UrlsItem)
  #define GTLPlusOnePersonImage                                       _GTL_NS_SYMBOL(GTLPlusOnePersonImage)
  #define GTLPlusOnePhotosFeed                                        _GTL_NS_SYMBOL(GTLPlusOnePhotosFeed)
  #define GTLPlusOnePhotosResource                                    _GTL_NS_SYMBOL(GTLPlusOnePhotosResource)
  #define GTLPlusOnePhotosResourceAlbum                               _GTL_NS_SYMBOL(GTLPlusOnePhotosResourceAlbum)
  #define GTLPlusOnePhotosResourceOwner                               _GTL_NS_SYMBOL(GTLPlusOnePhotosResourceOwner)
  #define GTLPlusOnePhotosResourceOwnerImage                          _GTL_NS_SYMBOL(GTLPlusOnePhotosResourceOwnerImage)
  #define GTLPlusOnePhotoTag                                          _GTL_NS_SYMBOL(GTLPlusOnePhotoTag)
  #define GTLPlusOnePhotoTagCoordinates                               _GTL_NS_SYMBOL(GTLPlusOnePhotoTagCoordinates)
  #define GTLPlusOnePhotoTagCoordinatesBottomRight                    _GTL_NS_SYMBOL(GTLPlusOnePhotoTagCoordinatesBottomRight)
  #define GTLPlusOnePhotoTagCoordinatesTopLeft                        _GTL_NS_SYMBOL(GTLPlusOnePhotoTagCoordinatesTopLeft)
  #define GTLPlusOnePhotoTagFeed                                      _GTL_NS_SYMBOL(GTLPlusOnePhotoTagFeed)
  #define GTLPlusOneVideo                                             _GTL_NS_SYMBOL(GTLPlusOneVideo)
  #define GTLPlusOneVideosFeed                                        _GTL_NS_SYMBOL(GTLPlusOneVideosFeed)
  #define GTLPredictionHostedModelOutput                              _GTL_NS_SYMBOL(GTLPredictionHostedModelOutput)
  #define GTLPredictionHostedModelOutputOutputMultiItem               _GTL_NS_SYMBOL(GTLPredictionHostedModelOutputOutputMultiItem)
  #define GTLPredictionInput                                          _GTL_NS_SYMBOL(GTLPredictionInput)
  #define GTLPredictionInputInput                                     _GTL_NS_SYMBOL(GTLPredictionInputInput)
  #define GTLPredictionOutput                                         _GTL_NS_SYMBOL(GTLPredictionOutput)
  #define GTLPredictionOutputOutputMultiItem                          _GTL_NS_SYMBOL(GTLPredictionOutputOutputMultiItem)
  #define GTLPredictionTraining                                       _GTL_NS_SYMBOL(GTLPredictionTraining)
  #define GTLPredictionTrainingModelInfo                              _GTL_NS_SYMBOL(GTLPredictionTrainingModelInfo)
  #define GTLPredictionUpdate                                         _GTL_NS_SYMBOL(GTLPredictionUpdate)
  #define GTLQuery                                                    _GTL_NS_SYMBOL(GTLQuery)
  #define GTLQueryBooks                                               _GTL_NS_SYMBOL(GTLQueryBooks)
  #define GTLQueryLatitude                                            _GTL_NS_SYMBOL(GTLQueryLatitude)
  #define GTLQueryModerator                                           _GTL_NS_SYMBOL(GTLQueryModerator)
  #define GTLQueryPlusOne                                             _GTL_NS_SYMBOL(GTLQueryPlusOne)
  #define GTLQueryPrediction                                          _GTL_NS_SYMBOL(GTLQueryPrediction)
  #define GTLQueryShopping                                            _GTL_NS_SYMBOL(GTLQueryShopping)
  #define GTLQueryTasks                                               _GTL_NS_SYMBOL(GTLQueryTasks)
  #define GTLQueryUrlShortener                                        _GTL_NS_SYMBOL(GTLQueryUrlShortener)
  #define GTLRuntimeCommon                                            _GTL_NS_SYMBOL(GTLRuntimeCommon)
  #define GTLService                                                  _GTL_NS_SYMBOL(GTLService)
  #define GTLServiceBooks                                             _GTL_NS_SYMBOL(GTLServiceBooks)
  #define GTLServiceLatitude                                          _GTL_NS_SYMBOL(GTLServiceLatitude)
  #define GTLServiceModerator                                         _GTL_NS_SYMBOL(GTLServiceModerator)
  #define GTLServicePlusOne                                           _GTL_NS_SYMBOL(GTLServicePlusOne)
  #define GTLServicePrediction                                        _GTL_NS_SYMBOL(GTLServicePrediction)
  #define GTLServiceShopping                                          _GTL_NS_SYMBOL(GTLServiceShopping)
  #define GTLServiceTasks                                             _GTL_NS_SYMBOL(GTLServiceTasks)
  #define GTLServiceTicket                                            _GTL_NS_SYMBOL(GTLServiceTicket)
  #define GTLServiceUrlShortener                                      _GTL_NS_SYMBOL(GTLServiceUrlShortener)
  #define GTLShoppingModelCategory                                    _GTL_NS_SYMBOL(GTLShoppingModelCategory)
  #define GTLShoppingModelDebug                                       _GTL_NS_SYMBOL(GTLShoppingModelDebug)
  #define GTLShoppingModelProduct                                     _GTL_NS_SYMBOL(GTLShoppingModelProduct)
  #define GTLShoppingModelProductAttributesItem                       _GTL_NS_SYMBOL(GTLShoppingModelProductAttributesItem)
  #define GTLShoppingModelProductAuthor                               _GTL_NS_SYMBOL(GTLShoppingModelProductAuthor)
  #define GTLShoppingModelProductImagesItem                           _GTL_NS_SYMBOL(GTLShoppingModelProductImagesItem)
  #define GTLShoppingModelProductImagesItemThumbnailsItem             _GTL_NS_SYMBOL(GTLShoppingModelProductImagesItemThumbnailsItem)
  #define GTLShoppingModelProductInventoriesItem                      _GTL_NS_SYMBOL(GTLShoppingModelProductInventoriesItem)
  #define GTLShoppingProduct                                          _GTL_NS_SYMBOL(GTLShoppingProduct)
  #define GTLShoppingProductRecommendationsItem                       _GTL_NS_SYMBOL(GTLShoppingProductRecommendationsItem)
  #define GTLShoppingProductRecommendationsItemRecommendationListItem _GTL_NS_SYMBOL(GTLShoppingProductRecommendationsItemRecommendationListItem)
  #define GTLShoppingProducts                                         _GTL_NS_SYMBOL(GTLShoppingProducts)
  #define GTLShoppingProductsFacetsItem                               _GTL_NS_SYMBOL(GTLShoppingProductsFacetsItem)
  #define GTLShoppingProductsFacetsItemBucketsItem                    _GTL_NS_SYMBOL(GTLShoppingProductsFacetsItemBucketsItem)
  #define GTLShoppingProductsPromotionsItem                           _GTL_NS_SYMBOL(GTLShoppingProductsPromotionsItem)
  #define GTLShoppingProductsPromotionsItemCustomFieldsItem           _GTL_NS_SYMBOL(GTLShoppingProductsPromotionsItemCustomFieldsItem)
  #define GTLShoppingProductsSpelling                                 _GTL_NS_SYMBOL(GTLShoppingProductsSpelling)
  #define GTLShoppingProductsStoresItem                               _GTL_NS_SYMBOL(GTLShoppingProductsStoresItem)
  #define GTLTasksTask                                                _GTL_NS_SYMBOL(GTLTasksTask)
  #define GTLTasksTaskList                                            _GTL_NS_SYMBOL(GTLTasksTaskList)
  #define GTLTasksTaskLists                                           _GTL_NS_SYMBOL(GTLTasksTaskLists)
  #define GTLTasksTasks                                               _GTL_NS_SYMBOL(GTLTasksTasks)
  #define GTLUrlShortenerAnalyticsSnapshot                            _GTL_NS_SYMBOL(GTLUrlShortenerAnalyticsSnapshot)
  #define GTLUrlShortenerAnalyticsSummary                             _GTL_NS_SYMBOL(GTLUrlShortenerAnalyticsSummary)
  #define GTLUrlShortenerStringCount                                  _GTL_NS_SYMBOL(GTLUrlShortenerStringCount)
  #define GTLUrlShortenerUrl                                          _GTL_NS_SYMBOL(GTLUrlShortenerUrl)
  #define GTLUrlShortenerUrlHistory                                   _GTL_NS_SYMBOL(GTLUrlShortenerUrlHistory)
  #define GTLUtilities                                                _GTL_NS_SYMBOL(GTLUtilities)
  #define GTMCachedURLResponse                                        _GTL_NS_SYMBOL(GTMCachedURLResponse)
  #define GTMCookieStorage                                            _GTL_NS_SYMBOL(GTMCookieStorage)
  #define GTMGatherInputStream                                        _GTL_NS_SYMBOL(GTMGatherInputStream)
  #define GTMHTTPFetcher                                              _GTL_NS_SYMBOL(GTMHTTPFetcher)
  #define GTMHTTPFetcherService                                       _GTL_NS_SYMBOL(GTMHTTPFetcherService)
  #define GTMHTTPFetchHistory                                         _GTL_NS_SYMBOL(GTMHTTPFetchHistory)
  #define GTMHTTPUploadFetcher                                        _GTL_NS_SYMBOL(GTMHTTPUploadFetcher)
  #define GTMMIMEDocument                                             _GTL_NS_SYMBOL(GTMMIMEDocument)
  #define GTMMIMEPart                                                 _GTL_NS_SYMBOL(GTMMIMEPart)
  #define GTMOAuth2Authentication                                     _GTL_NS_SYMBOL(GTMOAuth2Authentication)
  #define GTMOAuth2AuthorizationArgs                                  _GTL_NS_SYMBOL(GTMOAuth2AuthorizationArgs)
  #define GTMOAuth2SignIn                                             _GTL_NS_SYMBOL(GTMOAuth2SignIn)
  #define GTMOAuth2WindowController                                   _GTL_NS_SYMBOL(GTMOAuth2WindowController)
  #define GTMURLCache                                                 _GTL_NS_SYMBOL(GTMURLCache)

#endif
